TAGS = [
"#motivational",
"#motivation",
"#motivationalquotes",
"#inspiration",
"#quotes",
"#success",
"#inspirational",
"#inspirationalquotes",
"#quoteoftheday",
"#inspire",
"#entrepreneur",
"#positivevibes",
"#quote",
"#lifequotes",
"#motivate",
"#motivationmonday",
"#quotestoliveby",
"#motivationalquote",
"#entrepreneurlife",
"#successmindset",
"#motivationquotes",
"#entrepreneurship",
"#india",
"#quotestagram",
"#quotesaboutlife",
"#quotestoinspire",
"#quotestags",
"#quoted",
"#quotestoremember",
"#quotesilove",
"#quotelife",
"#quoteforyou",
"#successquote",
"#successful",
"#positivity",
"#positivequote",
"#quoteoftheweek",
"#inspireme",
"#inspiremindset",
"#indianquote",
"#makeinindia",
"#inspired",
"#inspiring",
"#successmantra",
"#successtips",
"#successforlife",
"#successsociety",
"#successstartwithyou",
"#successspiritual",
"#successsecret",
"#motivacao",
"#motiva",
"#motivacion",
"#positivevibe",
"#determination",
"#hardwork",
"#motivationeveryday",
"#motivationalquotesoftheday",
"#successgoals",
"#entrepreneurship101"

]

CAPTIONS = [
    "Follow @ai2motivate for more wisdom 😉",
    "Tag someone who needs to read this! Don’t allow your happiness to be dependent on the actions of others. 😇",
    "Drop a ❤️ if this resonates! Follow  @ai2motivate  for daily Quotes 😎",
    "For wise words follow @ai2motivate",
    "Comment down your thoughts 🙅🏻‍♂️",
    "Tag someone you admire for their self-belief 💜",
    "It is during our darkest moments that we must focus to see the light. \n   - Aristotle Onassis  \n \n 🌹🌹🌹Follow @ai2motivate 🌹🌹🌹",
    "Double tap if you agree 💯",
    "Let me know your opinion in the comments below💭",
    "For more content, hit that follow button now and join the community \n \n 👉🏻👉🏻👉🏻@ai2motivate 👈🏻👈🏻👈🏻",
    "TAG a person you think needs to see this📲"
    "Any Thoughts? 🤷🏻‍♂️",
    "The difference between who you are and who you want to be is what you do ",
    "Share if you liked the post to help us post more like this ❤️ ",
    "Like and share if you like it."
]